name: mind_journal
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.0
  sqflite: ^2.0.0+4
  path_provider: ^2.0.11
  intl: ^0.19.0
  shared_preferences: ^2.0.15
  table_calendar: ^3.1.2
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  sqflite_common_ffi: any
  
flutter:
  uses-material-design: true

  assets:
    - assets/fonts/

  fonts:
    - family: 'Buildingsandundertherailwaytracks'
      fonts:
        - asset: assets/fonts/Buildingsandundertherailwaytracks-Regular.otf
    - family: 'HannariMincho'
      fonts:
        - asset: assets/fonts/HannariMincho-Regular.otf
    - family: 'Yomogi'
      fonts:
        - asset: assets/fonts/Yomogi-Regular.ttf
    - family: 'KiwiMaru'
      fonts:
        - asset: assets/fonts/KiwiMaru-Regular.ttf
    - family: 'HannariMincho'
      fonts:
        - asset: assets/fonts/HannariMincho-Regular.otf
    - family: 'RocknRollOne'
      fonts:
        - asset: assets/fonts/RocknRollOne-Regular.ttf
    - family: 'DarumadropOne'
      fonts:
        - asset: assets/fonts/DarumadropOne-Regular.ttf         
    - family: 'TsukimiRounded'
      fonts:
        - asset: assets/fonts/TsukimiRounded-Regular.ttf
    - family: 'KaiseiTokumin'
      fonts:
        - asset: assets/fonts/KaiseiTokumin-Regular.ttf
    - family: 'HachiMaruPop'
      fonts:
        - asset: assets/fonts/HachiMaruPop-Regular.ttf
    - family: 'Stick'
      fonts:
        - asset: assets/fonts/Stick-Regular.ttf
    - family: 'MonomaniacOne'
      fonts:
        - asset: assets/fonts/MonomaniacOne-Regular.ttf
    - family: 'YuseiMagic'
      fonts:
        - asset: assets/fonts/YuseiMagic-Regular.ttf
    - family: 'SlacksideOne'
      fonts:
        - asset: assets/fonts/SlacksideOne-Regular.ttf
    - family: 'ShipporiMincho'
      fonts:
        - asset: assets/fonts/ShipporiMincho-Regular.ttf
    - family: 'KosugiMaru'
      fonts:
        - asset: assets/fonts/KosugiMaru-Regular.ttf
    - family: 'ZenKurenaido'
      fonts:
        - asset: assets/fonts/ZenKurenaido-Regular.ttf
    - family: 'KleeOne'
      fonts:
        - asset: assets/fonts/KleeOne-Regular.ttf
    - family: 'YujiSyuku'
      fonts:
        - asset: assets/fonts/YujiSyuku-Regular.ttf